# Generated by Django 3.0.3 on 2020-02-10 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='b_contact',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='b_email',
            field=models.EmailField(default='', max_length=110),
        ),
    ]
