# Generated by Django 3.0.3 on 2020-02-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0002_auto_20200211_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='b_pass',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='seller',
            name='s_pass',
            field=models.IntegerField(default=0),
        ),
    ]
