# Generated by Django 3.0.3 on 2020-02-11 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0004_auto_20200211_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='s_id',
            new_name='s_email',
        ),
    ]
