# Generated by Django 3.0.3 on 2020-02-11 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('H1', '0005_auto_20200211_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='s_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='H1.seller'),
        ),
    ]
